/**
 * gen-env.mjs
 * Runs as a prebuild step on Vercel (and any CI).
 * Reads environment variables and writes src/environments/environment.ts
 * so the Angular build has the keys it needs — without committing secrets to git.
 *
 * Set these in Vercel → Project → Settings → Environment Variables:
 *   GEMINI_API_KEY   →  your Gemini API key
 *   FORMSPREE_URL    →  https://formspree.io/f/<your-form-id>
 */
import { writeFileSync, mkdirSync } from 'fs';

const key = process.env['GEMINI_API_KEY'] ?? 'YOUR_GEMINI_API_KEY_HERE';
const url = process.env['FORMSPREE_URL']  ?? 'https://formspree.io/f/YOUR_FORM_ID';

mkdirSync('src/environments', { recursive: true });

writeFileSync(
  'src/environments/environment.ts',
  `// Auto-generated by scripts/gen-env.mjs — do not edit manually\nexport const environment = {\n  geminiApiKey: '${key}',\n  formspreeUrl: '${url}',\n};\n`,
);

console.log('[gen-env] ✓ src/environments/environment.ts written');
